### ISSUE TITLE
Change checkout path in codeql-action integration

### ISSUE THREAD

**Issue by achab** [crytic/amarna-action#6]
We've just added amarna-action to our CI. We had to change the last line of the yaml to make it work:

- currently (doesn't work, throws an error because location `'/github/workspace'` does not exist):
```yml
with:
  sarif_file: ${{ steps.amarna.outputs.sarif }}
  checkout_path: '/github/workspace'
```
- fix (file upload just works):
```yml
with:
  sarif_file: ${{ steps.amarna.outputs.sarif }}
  checkout_path: ${{ github.workspace }}
```
